import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head } from '@inertiajs/react';
import { BarChart, ColumnChart, DonutChart, LineChart } from '@/Components/AdminCharts';

const number = (value) => new Intl.NumberFormat('en-US').format(value ?? 0);
const title = (value) => String(value ?? '').replace(/[_-]/g, ' ').replace(/\b\w/g, (character) => character.toUpperCase());

export default function Reports({ auth, analytics }) {
	const summary = analytics?.summary ?? {};
	const serviceItems = Object.entries(analytics?.service_counts ?? {}).map(([label, value]) => ({ label, value }));
	const typeItems = Object.entries(analytics?.type_counts ?? {}).map(([label, value]) => ({ label, value }));
	const statusItems = Object.entries(analytics?.status_counts ?? {}).map(([label, value]) => ({ label: title(label), value }));
	const staff = analytics?.staff_performance ?? [];
	const inventory = analytics?.inventory ?? {};
	const areas = analytics?.areas ?? [];
	const plantedByArea = analytics?.planted_by_area ?? [];
	const plantedAreaTrend = plantedByArea.map((entry) => ({ label: entry.area, total: entry.trees }));

	return <AuthenticatedLayout user={auth.user} header={<h6>Reports</h6>}>
		<Head title="Reports" />
		<div className="space-y-6">
			<section className="relative overflow-hidden rounded-2xl bg-blue-950 px-5 py-6 text-white shadow-sm sm:px-7 sm:py-8"><div className="relative z-10 max-w-2xl"><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-blue-200">MENRO reporting</p><h1 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Operational reports</h1><p className="mt-2 text-sm leading-6 text-blue-100">Detailed service, workload, area, and inventory summaries generated from the current system records.</p></div><div className="absolute -right-10 -top-16 h-52 w-52 rounded-full border-[24px] border-blue-800/50" /></section>
			<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[['Appointments', summary.appointments], ['Members registered', summary.members], ['Requirements filed', summary.requirements], ['Seedlings available', summary.seedlings], ['Planted trees', summary.planted_trees]].map(([label, value]) => <div key={label} className="rounded-2xl border border-blue-100 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">{label}</p><p className="mt-3 text-2xl font-black text-blue-950">{number(value)}</p></div>)}</section>
			<section className="grid gap-5 xl:grid-cols-[1.35fr_1fr]"><div className="rounded-2xl border border-blue-100 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)] sm:p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-700">Annual volume</p><h2 className="mt-1 text-lg font-bold text-slate-800">Requests and completed work by month</h2><div className="mt-5"><LineChart data={analytics?.months ?? []} /></div></div><div className="rounded-2xl border border-blue-100 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)] sm:p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-700">Request mix</p><h2 className="mt-1 text-lg font-bold text-slate-800">Appointment types</h2><div className="mt-5"><DonutChart items={typeItems} /></div></div></section>
			<section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-blue-100 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)] sm:p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-700">Service demand</p><h2 className="mt-1 text-lg font-bold text-slate-800">Requests by service</h2><p className="mt-2 text-xs text-slate-500">Number of requests grouped by environmental service category.</p><div className="mt-5 rounded-xl border border-blue-50 bg-slate-50/60 p-4"><ColumnChart items={serviceItems} /></div></div><div className="rounded-2xl border border-blue-100 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)] sm:p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-700">Workflow</p><h2 className="mt-1 text-lg font-bold text-slate-800">Status distribution</h2><p className="mt-2 text-xs text-slate-500">Current appointment totals grouped by workflow status.</p><div className="mt-5 rounded-xl border border-blue-50 bg-slate-50/60 p-4"><ColumnChart items={statusItems} /></div></div></section>
			<section className="grid gap-5 lg:grid-cols-[1.15fr_1fr]"><div className="rounded-2xl border border-blue-100 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)] sm:p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-700">Field workload</p><h2 className="mt-1 text-lg font-bold text-slate-800">Staff performance</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[420px] text-left text-sm"><thead className="border-b border-slate-200 text-[10px] uppercase tracking-wide text-slate-400"><tr><th className="pb-3">Staff member</th><th className="pb-3">Assigned</th><th className="pb-3">Completed</th><th className="pb-3">Rate</th></tr></thead><tbody className="divide-y divide-slate-100">{staff.map((person) => <tr key={person.name}><td className="py-3 font-semibold text-slate-700">{person.name}</td><td className="py-3 text-slate-600">{person.assigned}</td><td className="py-3 text-slate-600">{person.completed}</td><td className="py-3 font-bold text-blue-700">{person.assigned ? Math.round((person.completed / person.assigned) * 100) : 0}%</td></tr>)}</tbody></table>{!staff.length && <p className="py-8 text-center text-sm text-slate-500">No assigned staff activity yet.</p>}</div></div><div className="rounded-2xl border border-blue-100 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)] sm:p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-700">Inventory report</p><h2 className="mt-1 text-lg font-bold text-slate-800">Request and stock position</h2><dl className="mt-5 grid grid-cols-2 gap-3">{[['Pending requests', inventory.pending], ['Approved requests', inventory.approved], ['Requested quantity', inventory.requested_quantity], ['Available stock', inventory.available_quantity]].map(([label, value]) => <div key={label} className="rounded-xl bg-blue-50/60 p-4"><dt className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-2 text-xl font-black text-blue-950">{number(value)}</dd></div>)}</dl><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-bold text-slate-700">Most requested seedlings</p><div className="mt-3 space-y-2">{(inventory.top_seedlings ?? []).map((seedling) => <div key={seedling.name} className="flex justify-between text-xs"><span className="text-slate-600">{seedling.name}</span><strong className="text-blue-700">{seedling.quantity}</strong></div>)}</div></div></div></section>
			<section className="rounded-2xl border border-blue-100 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)] sm:p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-700">Coverage</p><h2 className="mt-1 text-lg font-bold text-slate-800">Area activity</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="border-b border-slate-200 text-[10px] uppercase tracking-wide text-slate-400"><tr><th className="pb-3">Area</th><th className="pb-3">Type</th><th className="pb-3">Status</th><th className="pb-3">Appointments</th></tr></thead><tbody className="divide-y divide-slate-100">{areas.map((area) => <tr key={area.name}><td className="py-3 font-semibold text-slate-700">{area.name}</td><td className="py-3 text-slate-600">{area.type}</td><td className="py-3 capitalize text-slate-600">{area.status}</td><td className="py-3 font-bold text-blue-700">{area.appointments}</td></tr>)}</tbody></table>{!areas.length && <p className="py-8 text-center text-sm text-slate-500">No areas recorded yet.</p>}</div></section>
			<section className="rounded-2xl border border-blue-100 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)] sm:p-6"><div className="flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-700">Planting impact</p><h2 className="mt-1 text-lg font-bold text-slate-800">Trees planted by area</h2></div><span className="text-xs font-semibold text-slate-500">{number(summary.planted_trees)} total planted</span></div><p className="mt-2 text-sm text-slate-500">Approved inventory stock-outs linked to each appointment area.</p><div className="mt-6 rounded-xl border border-blue-50 bg-slate-50/60 p-4 sm:p-5"><LineChart data={plantedAreaTrend} /></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-slate-200 text-[10px] uppercase tracking-wide text-slate-400"><tr><th className="pb-3">Area</th><th className="pb-3">Trees planted</th><th className="pb-3">Inventory requests</th><th className="pb-3">Seedling varieties</th></tr></thead><tbody className="divide-y divide-slate-100">{plantedByArea.map((entry) => <tr key={entry.area}><td className="py-3 font-semibold text-slate-700">{entry.area}</td><td className="py-3 font-black text-blue-700">{number(entry.trees)}</td><td className="py-3 text-slate-600">{entry.requests}</td><td className="py-3 text-slate-600">{entry.seedlings.map((seedling) => `${seedling.name} (${seedling.quantity})`).join(', ')}</td></tr>)}</tbody></table>{!plantedByArea.length && <p className="py-8 text-center text-sm text-slate-500">No approved planting inventory has been recorded yet.</p>}</div></section>
		</div>
	</AuthenticatedLayout>;
}
